### ISSUE TITLE
Version 0.1.3 is broken 

### ISSUE THREAD

**Issue by alexanderleipzig** [mynewsdesk/social_media_parser#4]
this commit breaks the gem 9f1e3c29cbffc7dcf4ee33f9f11f0875ae64db3c

the line 
```
Dir.entries("lib/social_media_parser/provider/")
```

is not working when the gem is used in a rails app. it raises an

```
No such file or directory @ dir_initialize - lib/social_media_parser/provider/
```

My guess is, that the path is wrong when we are using the gem inside rails.
```
[2] pry(SocialMediaParser::Provider::Base)> Dir.pwd
=> "/Users/alexanderrothe/Projects/network-backend"
```

I did a binding.pry just before the failing line and you can see that the path is not the gem folder, its the rails root directory.

**Comment by himynameisjonas** [comment]
Fix this ASAP!!!

**Comment by himynameisjonas** [comment]
Ohai :)

**Comment by alexanderleipzig** [comment]
Hi! We could go back to the Array but this is ... a bit boring ;)

**Comment by martinsvalin** [comment]
`Dir.entries(__dir__)` could work. On my phone so I can't really check.

**Comment by mnordin** [comment]
Oh sorry @alexanderleipzig, totally missed this. Will look at this now

**Comment by mnordin** [comment]
Hmm, didn't know about `__dir__`, what a silly mistake. thx everyone! :love_hotel:
